[phases.setup]
nixpkgsArchive = "51ad838b03a05b1de6f9f2a0fffecee64a9788ee"
nixPkgs = ["nodejs_22", "python310", "gnumake", "gcc"]

[variables]
# This explicitly overrides Railway's auto-detected Turborepo command
NIXPACKS_BUILD_CMD = "yarn turbo run db:generate --filter=api && yarn turbo run build --filter=api"

[env]
npm_config_build_from_source = "false"

[phases.install]
cmds = [
  "corepack enable",
  "yarn install --immutable"
]

[start]
cmd = "node apps/api/dist/src/main.js"